//color folder icon: #0069ff
const WORK_LOCATION = {
  id: 1,
  type: "work",
  name: "Projects",
  icon: "/icons/finder/work.svg",
  kind: "folder",
  children: [
    {
      id: 5,
      name: "Soul Sync Website",
      icon: "/icons/finder/folder.svg",
      kind: "folder",
      children: [
        {
          id: 1,
          name: "SoulSync.txt",
          icon: "/icons/finder/txt.svg",
          kind: "file",
          fileType: "txt",
          description: [
            "Anonymous matchmaking web app based on zodiac signs, numerology, location, and interests, with real-time chat integration.",
            "• Designed and built the MongoDB database",
            "• Developed RESTful APIs, JWT authentication using Node.js, Express.js.",
            "• Implemented real-time chat using Socket.IO",
          ],
        },
        {
          id: 2,
          name: "SoulSync.png",
          icon: "/icons/finder/png.svg",
          kind: "file",
          fileType: "img",
          image: "/images/projects/SoulSync.png",
        },
        {
          id: 3,
          name: "soulsync.com",
          icon: "/icons/apps/safari.svg",
          kind: "file",
          fileType: "url",
          url: "https://soulsync-fe.pages.dev/",
        },

        {
          id: 4,
          name: "Source.github",
          icon: "/icons/finder/html.svg",
          kind: "file",
          fileType: "url",
          url: "https://github.com/nobitandoraemon/SoulSync-be",
        },
      ],
    },
    {
      id: 6,
      name: "JS Codefest 2025 SDK",
      icon: "/icons/finder/folder.svg",
      kind: "folder",
      children: [
        {
          id: 1,
          name: "Codefest.txt",
          icon: "/icons/finder/txt.svg",
          kind: "file",
          fileType: "txt",
          description: [
            "CodeFest is an academic event organized by JS Club, a coding competition where participants must program bots using specific commands to battle opponents, collect items, and overcome challenges, crafting unique strategies to win.",
            "J-Surviv is a battle royale game developed for a competition. Participated by 150+ coders",
            "CodeFest 2025 - SDK (Software Development Kit) is a toolkit designed to support contestants participating in CodeFest 2025.",
            "• Maintained and refactored the codebase from CodeFest 2024",
            "• Designed and added new features, items, and gameplay parameters",
            "• Used Java Socket.IO to receive and send data to the server",
            "• Supported players by explaining and guiding them on how to use the game kit / SDK",
          ],
        },
        {
          id: 2,
          name: "logo.png",
          icon: "/icons/finder/png.svg",
          kind: "file",
          fileType: "img",
          image: "/images/projects/codefest2025.png",
        },
        {
          id: 3,
          name: "j-surviv-game.png",
          icon: "/icons/finder/png.svg",
          kind: "file",
          fileType: "img",
          image: "/images/projects/j-surviv.png",
        },
        {
          id: 4,
          name: "landingpage.com",
          icon: "/icons/apps/safari.svg",
          kind: "file",
          fileType: "url",
          url: "https://codefest2025.jsclub.dev/",
        },
      ],
    },
    {
      id: 7,
      name: "thaivdOS Portfolio",
      icon: "/icons/finder/folder.svg",
      kind: "folder",
      children: [
        {
          id: 1,
          name: "Portfolio.txt",
          icon: "/icons/finder/txt.svg",
          kind: "file",
          fileType: "txt",
          subtitle: "thaivdOS Portfolio",
          description: [
            "A single-page personal website inspired by the macOS GUI and Javascript Mastery youtube channel, designed to deliver an interactive and visually engaging user interface.",
            "The project is built with Next.js 16, Tailwind CSS, while application state and window management are managed with Zustand and Immer. Animations are implemented using GSAP.",
          ],
        },
        {
          id: 2,
          name: "Portfolio.png",
          icon: "/icons/finder/png.svg",
          kind: "file",
          fileType: "img",
          image: "/images/projects/portfolio.png",
        },
        {
          id: 3,
          name: "Source.github",
          icon: "/icons/finder/html.svg",
          kind: "file",
          fileType: "url",
          url: "https://github.com/Kazelf/thaivdOS-portfolio",
        },
      ],
    },
    {
      id: 8,
      name: "When Dreams Are Forgotten",
      icon: "/icons/finder/folder.svg",
      kind: "folder",
      children: [
        {
          id: 1,
          name: "WDAF.txt",
          icon: "/icons/finder/txt.svg",
          kind: "file",
          fileType: "txt",
          description: [
            'Landing page for social project: "Khi ước mơ bị bỏ quên"(When Dreams Are Forgotten) helping young people find motivation to follow their dreams',
            "• Designed and built the page using Next.js, TailwindCSS.",
            "• Allowed young people share their stories about dreams.",
          ],
        },
        {
          id: 2,
          name: "LandingPage.png",
          icon: "/icons/finder/png.svg",
          kind: "file",
          fileType: "img",
          image: "/images/projects/wdaforgotten.png",
        },
        {
          id: 3,
          name: "khiuocmobi boquen.com",
          icon: "/icons/apps/safari.svg",
          kind: "file",
          fileType: "url",
          url: "https://khiuocmobiboquen.vercel.app",
        },

        {
          id: 4,
          name: "Source.github",
          icon: "/icons/finder/html.svg",
          kind: "file",
          fileType: "url",
          url: "https://github.com/Kazelf/whendreamsareforgotten-landingpage",
        },
      ],
    },
  ],
};

const ABOUT_LOCATION = {
  id: 2,
  type: "about",
  name: "About me",
  icon: "/icons/finder/about.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "about-me.txt",
      icon: "/icons/finder/txt.svg",
      kind: "file",
      fileType: "txt",
      image: "/images/vudinhthai.png",
      subtitle: "Hey, that's Thai!",
      description: [
        "📍Hanoi, Vietnam",
        "I am a student at FPT University with a 100% scholarship.",
        "Currently, I am focusing on becoming a <strong>Backend Developer</strong>, with my main technologies being <b>Node.js, Express.js</b>, and database tools such as <b>SQL Server, MongoDB</b>. I am opened to become a Fullstack Developer by having some projects using React.js, Next.js, and Tailwind CSS.",
        "My Email: vudinhthai081106@gmail.com",
        'Linkedin: <a href="https://www.linkedin.com/in/thaivd0811/" target="_blank"> https://www.linkedin.com/in/thaivd0811/ </a>',
      ],
    },
    {
      id: 2,
      name: "me.png",
      icon: "/icons/finder/png.svg",
      kind: "file",
      fileType: "img",
      image: "/images/thai.png",
    },
    {
      id: 3,
      name: "excellentStd.png",
      icon: "/icons/finder/png.svg",
      kind: "file",
      fileType: "img",
      image: "/images/ExcellentStudent.JPG",
    },
  ],
};

const RESUME_LOCATION = {
  id: 3,
  type: "resume",
  name: "Resume",
  icon: "/icons/finder/resume.svg",
  kind: "folder",
  children: [
    {
      id: 1,
      name: "resume.pdf",
      icon: "/icons/finder/pdf.svg",
      kind: "file",
      fileType: "url",
      url: "/files/resume.pdf",
    },
  ],
};

export const locations = {
  work: WORK_LOCATION,
  about: ABOUT_LOCATION,
  resume: RESUME_LOCATION,
};
